### ISSUE TITLE
NGINX not working with readOnlyRootFilesystem=true

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-baseline-regulated#10]
Dear @ckittel 

Good Day!

I have tried the NGINX ingress controller but it's not working with policy readOnlyRootFilesystem = true.
I have checked 
https://github.com/kubernetes/ingress-nginx/issues/6256
it seems like an issue with NGINX and pods are not getting provisioned with we keep readOnlyRootFilesystem = true.

Regards,

**Comment by ckittel** [comment]
Yeah, `readOnlyRootFilesystem` is not compatible with a lot of workloads.  ASP.NET containers even, as they require filesystem access for buffering events. I'm pretty sure we don't flag the deployment of the controller with a read only root filesystem, do we? Is that something you were experimenting with?

**Comment by nitinkhandelwal26** [comment]
Thank you @ckittel for your response.
Actually, I am experimenting with this :). 
NGINX pods are not provisioning with two policies : 
 "Rootonlyfilesystem" and "Kubernetes clusters should not allow container privilege escalation".

It works only when I exclude ingress controller namespace from these two policies.

Regards,

**Comment by ckittel** [comment]
Yeah, you'll have to tune exclusions in your Azure Policy to match the required capabilities of the content running in your cluster. You can consider having both a deny policy, where you know `readOnlyRootFilesystem: true` is acceptable, and an Audit policy for everything else (the whole cluster).  That way you are at least keeping track of those containers that have that setting enabled, and blocking it where it should be blocked.

**Comment by nitinkhandelwal26** [comment]
Thanks @ckittel
