### ISSUE TITLE
In ClusterStamp.json in saved searches section "traefik_entrypoint_requests_total" is used where as we are not using Traefik ingress

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-baseline-regulated#26]
Hello Team,

I just noticed, in clusterstamp.v2.json if I go to the saved searches section at line 888, in query "traefik_entrypoint_requests_total" filter is used.

Please check it's still relevant to this implementation? as we are using NGINX ingress in this.

Regards,

**Comment by ckittel** [comment]
Thank you, that was indeed an oversight after the ingress change.  I'll add it to our backlog to remove/change.

**Comment by ckittel** [comment]
@nitinkhandelwal26 I've captured this in our internal backlog (Ref 468514), and have scheduled that change for about two weeks from now (next sprint).  I'll leave this issue open until it is resolved though.
