### ISSUE TITLE
Do not find OSM manifest

### ISSUE THREAD

**Issue by liuzhiyong1982** [mspnp/aks-baseline-regulated#29]
Cluster workload utility, Open Service Mesh (see: osm-system),  the link leads to 404 and do not find OSM manifest in repository. Can we use Istio to replace OSM?

**Comment by liuzhiyong1982** [comment]
I think I find it in kube-system folder.

**Comment by ckittel** [comment]
You're welcome to use any service mesh (or no service mesh) as you wish.

I'll try to track down the link you're talking about and update it so that it's not a 404.  If you have any specifics on where I can find that link @liuzhiyong1982, let me know otherwise I'll just search for it.

**Comment by ckittel** [comment]
I've updated that page, thank you for letting us know!

You won't find the manifest to deploy OSM, as that is being handled as an AKS add-on.  Just the configuration of OSM is included as a manifest file.
