### ISSUE TITLE
get  error on EnsureClusterIdentityHasRbacToSelfManagedResources 

### ISSUE THREAD

**Issue by liuzhiyong1982** [mspnp/aks-baseline-regulated#43]
When I attempt to deploy cluster-stamp.json, always get error on EnsureClusterIdentityHasRbacToSelfManagedResources deployment.  I noticed there are actually 6 roleAssignments in this block. 4 of them regarding MI RBAC role assignments to subnet scope get the same error msg:
{
    "status": "Failed",
    "error": {
        "code": "RoleAssignmentUpdateNotPermitted",
        "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
}
 
From my understanding, RBAC can only be applied on 1) Resource Groups 2) Resource (vnet is a resource and not subnets, subnets are the outcome of a resource) 3) Subscription
Subnets are not resources and you will not be able to restrict which subnets can and cannot be used, via RBAC/Custom roles feature.
Feel to correct me if I am wrong.

**Comment by ckittel** [comment]
Going to close this one as there haven't been any updates in about a month.  Feel free to open a new issue or this one to continue the conversation. Thanks!
