### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by liuzhiyong1982** [mspnp/aks-baseline-regulated#81]
Do you have plan to implement the infrastructure via Terraform in the near future? Terraform is also a popular IaC tool which should be under your radar. 
Thank you in advance.

**Comment by ckittel** [comment]
Yes, you can find a roughly-similar terraform implementation at https://github.com/Azure/aks-baseline-automation -- it's not a direct port of this implementation, but is not too far off (was based itself on the AKS baseline, which this repo is too based on).  It should make a great starting point for your own implementation.  This repo will not be getting a Terraform implementation itself.

**Comment by liuzhiyong1982** [comment]
That is good enough . Thank you .
